FROM lmchallenge

RUN pip3 install --upgrade                \
    coveralls                             \
    Faker                                 \
    flake8                                \
    flake8-copyright                      \
    jupyter                               \
    matplotlib                            \
    numpy                                 \
    pandas                                \
    recommonmark                          \
    scipy                                 \
    seaborn                               \
    setuptools                            \
    sphinx                                \
    sphinx-argparse                       \
    sphinx_rtd_theme
